# config.yaml
# dataloader:
#   batch_size: 32
#   num_workers: 4
#   train_size: 0.8
# model:
#   hidden_units: 128
#   learning_rate: 0.001
batch_size: 64
images_path: "data\\images"
mask_path: "data\\mask"
log_filename: 'app.log'